<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'name'              => 'Santorini',
                'country'           => 'Greece',
                'city'              => 'Santorini',
                'category'          => 'Beach',
                'image'             => 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=85',
                'gallery'           => [
                    'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=600&q=80',
                    'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&q=80',
                    'https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=600&q=80',
                ],
                'short_description' => 'Iconic white-washed villages perched on volcanic cliffs above the Aegean Sea.',
                'description'       => 'Santorini is a stunning Greek island in the southern Aegean Sea, known worldwide for its dramatic views, white-washed architecture with iconic blue domes, and spectacular sunsets. The island was formed by a massive volcanic eruption and the caldera offers a breathtaking backdrop to every vista. Explore the narrow, winding streets of Oia and Fira, indulge in world-class cuisine, and discover ancient ruins that speak of millennia of rich history.',
                'highlights'        => ['Oia Sunset Viewpoint', 'Caldera Views', 'Black Sand Beaches', 'Ancient Akrotiri Ruins', 'Local Wine Tasting'],
                'activities'        => ['Catamaran Cruise', 'Volcano Hiking', 'Wine Tour', 'Scuba Diving', 'Photography Tours'],
                'best_time'         => 'April – October',
                'estimated_budget'  => '$120–$300/day',
                'rating'            => 4.9,
                'reviews_count'     => 12480,
                'is_featured'       => true,
                'is_popular'        => true,
                'latitude'          => 36.3932,
                'longitude'         => 25.4615,
            ],
            [
                'name'              => 'Kyoto',
                'country'           => 'Japan',
                'city'              => 'Kyoto',
                'category'          => 'Cultural',
                'image'             => 'https://images.unsplash.com/photo-1624253321171-1be53e12f5f4?w=800&q=85',
                'gallery'           => [
                    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80',
                    'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80',
                    'https://images.unsplash.com/photo-1460374886801-fd06e33e65a8?w=600&q=80',
                ],
                'short_description' => 'Ancient temples, bamboo forests, and timeless geisha culture in Japan\'s old capital.',
                'description'       => 'Kyoto served as Japan\'s imperial capital for over a thousand years, and today it stands as the cultural heart of the nation. With over 1,600 Buddhist temples and 400 Shinto shrines, world-famous geisha districts, and stunning seasonal landscapes — from spring cherry blossoms to blazing autumn maples — Kyoto offers an unparalleled cultural experience. Walk the Philosopher\'s Path, explore Arashiyama\'s bamboo groves, and witness the golden splendor of Kinkaku-ji.',
                'highlights'        => ['Fushimi Inari Shrine', 'Arashiyama Bamboo Grove', 'Kinkaku-ji Golden Pavilion', 'Gion Geisha District', 'Nishiki Market'],
                'activities'        => ['Tea Ceremony', 'Geisha Show', 'Temple Hopping', 'Kimono Rental', 'Cooking Class'],
                'best_time'         => 'March – May, Oct – Nov',
                'estimated_budget'  => '$80–$200/day',
                'rating'            => 4.8,
                'reviews_count'     => 18920,
                'is_featured'       => false,
                'is_popular'        => true,
                'latitude'          => 35.0116,
                'longitude'         => 135.7681,
            ],
            [
                'name'              => 'Machu Picchu',
                'country'           => 'Peru',
                'city'              => 'Aguas Calientes',
                'category'          => 'Adventure',
                'image'             => 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=85',
                'gallery'           => [
                    'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600&q=80',
                    'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=600&q=80',
                    'https://images.unsplash.com/photo-1574015974293-817f0ebebb74?w=600&q=80',
                ],
                'short_description' => 'The legendary "Lost City of the Incas" shrouded in clouds above the Urubamba River.',
                'description'       => 'Machu Picchu, built in the 15th century by the Inca Empire, is one of humanity\'s greatest architectural achievements. Perched at 2,430 meters above sea level on a mountain ridge above the Sacred Valley, this citadel was hidden from the Spanish conquistadors and only rediscovered in 1911. Today it stands as a UNESCO World Heritage Site and one of the New Seven Wonders of the World. The journey to reach it — whether by train or the legendary Inca Trail — is as breathtaking as the destination itself.',
                'highlights'        => ['Inca Trail Trek', 'Sun Gate (Inti Punku)', 'Huayna Picchu Summit', 'Temple of the Sun', 'Agricultural Terraces'],
                'activities'        => ['Inca Trail Hiking', 'Llama Spotting', 'Sunrise Viewing', 'Photography', 'Guided Archaeological Tour'],
                'best_time'         => 'April – October (dry season)',
                'estimated_budget'  => '$60–$150/day',
                'rating'            => 4.9,
                'reviews_count'     => 15670,
                'is_featured'       => false,
                'is_popular'        => true,
                'latitude'          => -13.1631,
                'longitude'         => -72.5450,
            ],
            [
                'name'              => 'Bali',
                'country'           => 'Indonesia',
                'city'              => 'Ubud',
                'category'          => 'Nature',
                'image'             => 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=85',
                'gallery'           => [
                    'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',
                    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
                    'https://images.unsplash.com/photo-1531778272849-d1dd22444c06?w=600&q=80',
                ],
                'short_description' => 'Terraced rice paddies, sacred temples, and spiritual retreats on the Island of the Gods.',
                'description'       => 'Bali is a living postcard of tropical beauty and deep spiritual culture. The island\'s emerald-green rice terraces, ancient Hindu temples, and welcoming Balinese culture have made it one of the world\'s most beloved destinations. From the artistic hub of Ubud to the surf paradise of Seminyak, each region offers a distinct personality. Whether you seek yoga retreats, world-class diving, vibrant nightlife, or pure cultural immersion, Bali delivers an experience unlike anywhere else on Earth.',
                'highlights'        => ['Tegallalang Rice Terraces', 'Tanah Lot Sea Temple', 'Sacred Monkey Forest', 'Mount Batur Sunrise Trek', 'Seminyak Beach Clubs'],
                'activities'        => ['Yoga & Meditation', 'Surfing', 'Temple Tours', 'Cooking Class', 'Waterfall Hiking'],
                'best_time'         => 'April – September',
                'estimated_budget'  => '$40–$120/day',
                'rating'            => 4.7,
                'reviews_count'     => 24310,
                'is_featured'       => false,
                'is_popular'        => true,
                'latitude'          => -8.5069,
                'longitude'         => 115.2625,
            ],
            [
                'name'              => 'Amalfi Coast',
                'country'           => 'Italy',
                'city'              => 'Positano',
                'category'          => 'Beach',
                'image'             => 'https://images.unsplash.com/photo-1612698093158-e07ac200d44e?w=800&q=85',
                'gallery'           => [
                    'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=600&q=80',
                    'https://images.unsplash.com/photo-1555992828-ca4dbe41d294?w=600&q=80',
                    'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=600&q=80',
                ],
                'short_description' => 'Pastel-hued clifftop villages cascading to turquoise Mediterranean waters.',
                'description'       => 'The Amalfi Coast is a 50-kilometre stretch of coastline along the southern edge of Italy\'s Sorrentine Peninsula, celebrated as one of Europe\'s most scenic drives. The dramatic cliffs are dotted with colourful villages, vineyards, lemon groves, and hidden beaches. Positano, Ravello, and Amalfi town each have their own distinct charm. The area is a UNESCO World Heritage Site and has inspired artists, writers, and lovers for centuries. Fresh seafood, local limoncello, and breathtaking views await at every turn.',
                'highlights'        => ['Positano Village', 'Path of the Gods Hike', 'Ravello Gardens', 'Fiordo di Furore', 'Amalfi Cathedral'],
                'activities'        => ['Boat Tours', 'Cliff Diving', 'Limoncello Tasting', 'Coastal Hiking', 'Kayaking'],
                'best_time'         => 'May – June, September',
                'estimated_budget'  => '$150–$350/day',
                'rating'            => 4.8,
                'reviews_count'     => 9840,
                'is_featured'       => false,
                'is_popular'        => true,
                'latitude'          => 40.6280,
                'longitude'         => 14.4850,
            ],
            [
                'name'              => 'Patagonia',
                'country'           => 'Argentina & Chile',
                'city'              => 'El Calafate',
                'category'          => 'Mountain',
                'image'             => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=85',
                'gallery'           => [
                    'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=600&q=80',
                    'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=80',
                    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80',
                ],
                'short_description' => 'Untamed wilderness of glaciers, granite spires, and vast Andean steppes at the end of the world.',
                'description'       => 'Patagonia stretches across the southern end of South America, shared between Argentina and Chile, offering some of the planet\'s most raw and awe-inspiring landscapes. From the iconic granite towers of Torres del Paine to the Perito Moreno Glacier where you can hear the thunderous crack of calving ice, this region is a paradise for adventure travelers and nature lovers. The region\'s remoteness and pristine ecosystems make every expedition feel like a true adventure into the unknown.',
                'highlights'        => ['Perito Moreno Glacier', 'Torres del Paine Towers', 'W-Trek & O-Trek', 'Los Glaciares National Park', 'Tierra del Fuego'],
                'activities'        => ['Glacier Trekking', 'Rock Climbing', 'Wildlife Spotting', 'Kayaking', 'Fly Fishing'],
                'best_time'         => 'November – March',
                'estimated_budget'  => '$80–$200/day',
                'rating'            => 4.9,
                'reviews_count'     => 7520,
                'is_featured'       => false,
                'is_popular'        => true,
                'latitude'          => -50.3400,
                'longitude'         => -72.2646,
            ],
            [
                'name'              => 'Marrakech',
                'country'           => 'Morocco',
                'city'              => 'Marrakech',
                'category'          => 'Cultural',
                'image'             => 'https://images.unsplash.com/photo-1597212618440-806262de4f8b?w=800&q=85',
                'gallery'           => [
                    'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=600&q=80',
                    'https://images.unsplash.com/photo-1553603227-2358aabe821e?w=600&q=80',
                    'https://images.unsplash.com/photo-1587974928442-e65d39e84be8?w=600&q=80',
                ],
                'short_description' => 'A sensory feast of spice-scented souks, ornate riads, and rose-gold desert sunsets.',
                'description'       => 'Marrakech is a city of extraordinary contrasts — a labyrinthine medina where medieval tradition meets modern creativity. The fabled Djemaa el-Fna square transforms from a chaotic daytime market into a mesmerizing evening spectacle of storytellers, musicians, and food stalls. Explore the intricate architecture of ancient palaces and mosques, lose yourself in the colorful souks of the medina, and retreat to the tranquil courtyards of luxurious riads. The Atlas Mountains and Sahara Desert are just hours away.',
                'highlights'        => ['Djemaa el-Fna Square', 'Bahia Palace', 'Majorelle Garden', 'Medina Souks', 'Ben Youssef Madrasa'],
                'activities'        => ['Souk Shopping', 'Cooking Class', 'Hammam Experience', 'Desert Day Trip', 'Riad Stay'],
                'best_time'         => 'March – May, September – November',
                'estimated_budget'  => '$50–$150/day',
                'rating'            => 4.6,
                'reviews_count'     => 11230,
                'is_featured'       => false,
                'is_popular'        => true,
                'latitude'          => 31.6295,
                'longitude'         => -7.9811,
            ],
            [
                'name'              => 'New York City',
                'country'           => 'United States',
                'city'              => 'New York',
                'category'          => 'City',
                'image'             => 'https://images.unsplash.com/photo-1538970272646-f61fabb3a8a2?w=800&q=85',
                'gallery'           => [
                    'https://images.unsplash.com/photo-1490644658840-3f2e3f8c5625?w=600&q=80',
                    'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=600&q=80',
                    'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=600&q=80',
                ],
                'short_description' => 'The city that never sleeps — culture, cuisine, skylines, and endless urban energy.',
                'description'       => 'New York City is the ultimate urban destination — a sprawling metropolis of iconic skylines, world-class museums, legendary food scenes, and a cultural energy unlike anywhere on Earth. Manhattan\'s grid pulses with life 24/7, from the neon spectacle of Times Square to the green oasis of Central Park. Brooklyn\'s creative neighborhoods, the High Line\'s elevated gardens, and the Statue of Liberty\'s enduring symbolism all contribute to a city that rewards explorers on every visit, offering something new no matter how many times you return.',
                'highlights'        => ['Central Park', 'Brooklyn Bridge', 'Metropolitan Museum of Art', 'High Line Park', 'Statue of Liberty'],
                'activities'        => ['Broadway Shows', 'Museum Hopping', 'Food Tours', 'Rooftop Bars', 'Helicopter Tour'],
                'best_time'         => 'April – June, September – November',
                'estimated_budget'  => '$150–$400/day',
                'rating'            => 4.7,
                'reviews_count'     => 31540,
                'is_featured'       => false,
                'is_popular'        => true,
                'latitude'          => 40.7128,
                'longitude'         => -74.0060,
            ],
        ];

        foreach ($destinations as $data) {
            $data['slug'] = Str::slug($data['name']);
            Destination::create($data);
        }
    }
}
